flink:
  app:
    name: TDQ - RT Metric Collector - Prod
    checkpoint:
      data-dir: /tmp/flink/checkpoints/tdq-rt-metric-collector/
    parallelism:
      default: 100
      source: 200
    watermark:
      max-out-of-orderness-in-min: 1
      idle-source-timeout-in-min: 10
    source:
      kafka:
        group-id: tdq-prod-rt-metric-collector
        env: prod
        stream: behavior.totalv3
        dc: rno
        topic:
          - behavior.totalv3.sojevent-nonbot-rno
        from-timestamp: latest

rheos:
  registry-url: https://rheos-services.stratus.ebay.com
  client:
    auth-type: TRUST_FABRIC

pronto:
  scheme: https
  host: estdq-datalvs.vip.ebay.com
  port: 443
  username: 94259ed8d74742c585a7b86faf3d0001
  password: 7s3AG1ZqOwjz9X59UbPNtcJcb1a0OvMYqDSvGigS2ArjctmBy9YkYIGHxLWcCdky
