/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ebay.dap.tdq.common.model.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AnyId extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1488045746823110373L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AnyId\",\"namespace\":\"com.ebay.dap.tdq.common.model.avro\",\"fields\":[{\"name\":\"val\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"AnyId value\",\"default\":\"\"},{\"name\":\"xt\",\"type\":{\"type\":\"array\",\"items\":\"long\"},\"doc\":\"set of experienced treatmentids for this AnyId value\",\"default\":[]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AnyId> ENCODER =
      new BinaryMessageEncoder<AnyId>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AnyId> DECODER =
      new BinaryMessageDecoder<AnyId>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AnyId> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AnyId> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AnyId> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AnyId>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AnyId to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AnyId from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AnyId instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AnyId fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** AnyId value */
   private java.lang.String val;
  /** set of experienced treatmentids for this AnyId value */
   private java.util.List<java.lang.Long> xt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AnyId() {}

  /**
   * All-args constructor.
   * @param val AnyId value
   * @param xt set of experienced treatmentids for this AnyId value
   */
  public AnyId(java.lang.String val, java.util.List<java.lang.Long> xt) {
    this.val = val;
    this.xt = xt;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return val;
    case 1: return xt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: val = value$ != null ? value$.toString() : null; break;
    case 1: xt = (java.util.List<java.lang.Long>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'val' field.
   * @return AnyId value
   */
  public java.lang.String getVal() {
    return val;
  }


  /**
   * Sets the value of the 'val' field.
   * AnyId value
   * @param value the value to set.
   */
  public void setVal(java.lang.String value) {
    this.val = value;
  }

  /**
   * Gets the value of the 'xt' field.
   * @return set of experienced treatmentids for this AnyId value
   */
  public java.util.List<java.lang.Long> getXt() {
    return xt;
  }


  /**
   * Sets the value of the 'xt' field.
   * set of experienced treatmentids for this AnyId value
   * @param value the value to set.
   */
  public void setXt(java.util.List<java.lang.Long> value) {
    this.xt = value;
  }

  /**
   * Creates a new AnyId RecordBuilder.
   * @return A new AnyId RecordBuilder
   */
  public static com.ebay.dap.tdq.common.model.avro.AnyId.Builder newBuilder() {
    return new com.ebay.dap.tdq.common.model.avro.AnyId.Builder();
  }

  /**
   * Creates a new AnyId RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AnyId RecordBuilder
   */
  public static com.ebay.dap.tdq.common.model.avro.AnyId.Builder newBuilder(com.ebay.dap.tdq.common.model.avro.AnyId.Builder other) {
    if (other == null) {
      return new com.ebay.dap.tdq.common.model.avro.AnyId.Builder();
    } else {
      return new com.ebay.dap.tdq.common.model.avro.AnyId.Builder(other);
    }
  }

  /**
   * Creates a new AnyId RecordBuilder by copying an existing AnyId instance.
   * @param other The existing instance to copy.
   * @return A new AnyId RecordBuilder
   */
  public static com.ebay.dap.tdq.common.model.avro.AnyId.Builder newBuilder(com.ebay.dap.tdq.common.model.avro.AnyId other) {
    if (other == null) {
      return new com.ebay.dap.tdq.common.model.avro.AnyId.Builder();
    } else {
      return new com.ebay.dap.tdq.common.model.avro.AnyId.Builder(other);
    }
  }

  /**
   * RecordBuilder for AnyId instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AnyId>
    implements org.apache.avro.data.RecordBuilder<AnyId> {

    /** AnyId value */
    private java.lang.String val;
    /** set of experienced treatmentids for this AnyId value */
    private java.util.List<java.lang.Long> xt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ebay.dap.tdq.common.model.avro.AnyId.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.val)) {
        this.val = data().deepCopy(fields()[0].schema(), other.val);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.xt)) {
        this.xt = data().deepCopy(fields()[1].schema(), other.xt);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing AnyId instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ebay.dap.tdq.common.model.avro.AnyId other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.val)) {
        this.val = data().deepCopy(fields()[0].schema(), other.val);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.xt)) {
        this.xt = data().deepCopy(fields()[1].schema(), other.xt);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'val' field.
      * AnyId value
      * @return The value.
      */
    public java.lang.String getVal() {
      return val;
    }


    /**
      * Sets the value of the 'val' field.
      * AnyId value
      * @param value The value of 'val'.
      * @return This builder.
      */
    public com.ebay.dap.tdq.common.model.avro.AnyId.Builder setVal(java.lang.String value) {
      validate(fields()[0], value);
      this.val = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'val' field has been set.
      * AnyId value
      * @return True if the 'val' field has been set, false otherwise.
      */
    public boolean hasVal() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'val' field.
      * AnyId value
      * @return This builder.
      */
    public com.ebay.dap.tdq.common.model.avro.AnyId.Builder clearVal() {
      val = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'xt' field.
      * set of experienced treatmentids for this AnyId value
      * @return The value.
      */
    public java.util.List<java.lang.Long> getXt() {
      return xt;
    }


    /**
      * Sets the value of the 'xt' field.
      * set of experienced treatmentids for this AnyId value
      * @param value The value of 'xt'.
      * @return This builder.
      */
    public com.ebay.dap.tdq.common.model.avro.AnyId.Builder setXt(java.util.List<java.lang.Long> value) {
      validate(fields()[1], value);
      this.xt = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'xt' field has been set.
      * set of experienced treatmentids for this AnyId value
      * @return True if the 'xt' field has been set, false otherwise.
      */
    public boolean hasXt() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'xt' field.
      * set of experienced treatmentids for this AnyId value
      * @return This builder.
      */
    public com.ebay.dap.tdq.common.model.avro.AnyId.Builder clearXt() {
      xt = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AnyId build() {
      try {
        AnyId record = new AnyId();
        record.val = fieldSetFlags()[0] ? this.val : (java.lang.String) defaultValue(fields()[0]);
        record.xt = fieldSetFlags()[1] ? this.xt : (java.util.List<java.lang.Long>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AnyId>
    WRITER$ = (org.apache.avro.io.DatumWriter<AnyId>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AnyId>
    READER$ = (org.apache.avro.io.DatumReader<AnyId>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.val);

    long size0 = this.xt.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.Long e0: this.xt) {
      actualSize0++;
      out.startItem();
      out.writeLong(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.val = in.readString();

      long size0 = in.readArrayStart();
      java.util.List<java.lang.Long> a0 = this.xt;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.Long>((int)size0, SCHEMA$.getField("xt").schema());
        this.xt = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.Long> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.Long>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.Long e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readLong();
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.val = in.readString();
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.Long> a0 = this.xt;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.Long>((int)size0, SCHEMA$.getField("xt").schema());
            this.xt = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.Long> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.Long>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.Long e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readLong();
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










