/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ebay.dap.tdq.common.model.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class DeviceDetection extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 1236285590137414165L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"DeviceDetection\",\"namespace\":\"com.ebay.dap.tdq.common.model.avro\",\"fields\":[{\"name\":\"formFactor\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"experience\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"model\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<DeviceDetection> ENCODER =
      new BinaryMessageEncoder<DeviceDetection>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<DeviceDetection> DECODER =
      new BinaryMessageDecoder<DeviceDetection>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<DeviceDetection> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<DeviceDetection> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<DeviceDetection> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<DeviceDetection>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this DeviceDetection to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a DeviceDetection from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a DeviceDetection instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static DeviceDetection fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.String formFactor;
   private java.lang.String experience;
   private java.lang.String model;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public DeviceDetection() {}

  /**
   * All-args constructor.
   * @param formFactor The new value for formFactor
   * @param experience The new value for experience
   * @param model The new value for model
   */
  public DeviceDetection(java.lang.String formFactor, java.lang.String experience, java.lang.String model) {
    this.formFactor = formFactor;
    this.experience = experience;
    this.model = model;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return formFactor;
    case 1: return experience;
    case 2: return model;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: formFactor = value$ != null ? value$.toString() : null; break;
    case 1: experience = value$ != null ? value$.toString() : null; break;
    case 2: model = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'formFactor' field.
   * @return The value of the 'formFactor' field.
   */
  public java.lang.String getFormFactor() {
    return formFactor;
  }


  /**
   * Sets the value of the 'formFactor' field.
   * @param value the value to set.
   */
  public void setFormFactor(java.lang.String value) {
    this.formFactor = value;
  }

  /**
   * Gets the value of the 'experience' field.
   * @return The value of the 'experience' field.
   */
  public java.lang.String getExperience() {
    return experience;
  }


  /**
   * Sets the value of the 'experience' field.
   * @param value the value to set.
   */
  public void setExperience(java.lang.String value) {
    this.experience = value;
  }

  /**
   * Gets the value of the 'model' field.
   * @return The value of the 'model' field.
   */
  public java.lang.String getModel() {
    return model;
  }


  /**
   * Sets the value of the 'model' field.
   * @param value the value to set.
   */
  public void setModel(java.lang.String value) {
    this.model = value;
  }

  /**
   * Creates a new DeviceDetection RecordBuilder.
   * @return A new DeviceDetection RecordBuilder
   */
  public static com.ebay.dap.tdq.common.model.avro.DeviceDetection.Builder newBuilder() {
    return new com.ebay.dap.tdq.common.model.avro.DeviceDetection.Builder();
  }

  /**
   * Creates a new DeviceDetection RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new DeviceDetection RecordBuilder
   */
  public static com.ebay.dap.tdq.common.model.avro.DeviceDetection.Builder newBuilder(com.ebay.dap.tdq.common.model.avro.DeviceDetection.Builder other) {
    if (other == null) {
      return new com.ebay.dap.tdq.common.model.avro.DeviceDetection.Builder();
    } else {
      return new com.ebay.dap.tdq.common.model.avro.DeviceDetection.Builder(other);
    }
  }

  /**
   * Creates a new DeviceDetection RecordBuilder by copying an existing DeviceDetection instance.
   * @param other The existing instance to copy.
   * @return A new DeviceDetection RecordBuilder
   */
  public static com.ebay.dap.tdq.common.model.avro.DeviceDetection.Builder newBuilder(com.ebay.dap.tdq.common.model.avro.DeviceDetection other) {
    if (other == null) {
      return new com.ebay.dap.tdq.common.model.avro.DeviceDetection.Builder();
    } else {
      return new com.ebay.dap.tdq.common.model.avro.DeviceDetection.Builder(other);
    }
  }

  /**
   * RecordBuilder for DeviceDetection instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<DeviceDetection>
    implements org.apache.avro.data.RecordBuilder<DeviceDetection> {

    private java.lang.String formFactor;
    private java.lang.String experience;
    private java.lang.String model;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ebay.dap.tdq.common.model.avro.DeviceDetection.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.formFactor)) {
        this.formFactor = data().deepCopy(fields()[0].schema(), other.formFactor);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.experience)) {
        this.experience = data().deepCopy(fields()[1].schema(), other.experience);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.model)) {
        this.model = data().deepCopy(fields()[2].schema(), other.model);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing DeviceDetection instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ebay.dap.tdq.common.model.avro.DeviceDetection other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.formFactor)) {
        this.formFactor = data().deepCopy(fields()[0].schema(), other.formFactor);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.experience)) {
        this.experience = data().deepCopy(fields()[1].schema(), other.experience);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.model)) {
        this.model = data().deepCopy(fields()[2].schema(), other.model);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'formFactor' field.
      * @return The value.
      */
    public java.lang.String getFormFactor() {
      return formFactor;
    }


    /**
      * Sets the value of the 'formFactor' field.
      * @param value The value of 'formFactor'.
      * @return This builder.
      */
    public com.ebay.dap.tdq.common.model.avro.DeviceDetection.Builder setFormFactor(java.lang.String value) {
      validate(fields()[0], value);
      this.formFactor = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'formFactor' field has been set.
      * @return True if the 'formFactor' field has been set, false otherwise.
      */
    public boolean hasFormFactor() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'formFactor' field.
      * @return This builder.
      */
    public com.ebay.dap.tdq.common.model.avro.DeviceDetection.Builder clearFormFactor() {
      formFactor = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'experience' field.
      * @return The value.
      */
    public java.lang.String getExperience() {
      return experience;
    }


    /**
      * Sets the value of the 'experience' field.
      * @param value The value of 'experience'.
      * @return This builder.
      */
    public com.ebay.dap.tdq.common.model.avro.DeviceDetection.Builder setExperience(java.lang.String value) {
      validate(fields()[1], value);
      this.experience = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'experience' field has been set.
      * @return True if the 'experience' field has been set, false otherwise.
      */
    public boolean hasExperience() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'experience' field.
      * @return This builder.
      */
    public com.ebay.dap.tdq.common.model.avro.DeviceDetection.Builder clearExperience() {
      experience = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'model' field.
      * @return The value.
      */
    public java.lang.String getModel() {
      return model;
    }


    /**
      * Sets the value of the 'model' field.
      * @param value The value of 'model'.
      * @return This builder.
      */
    public com.ebay.dap.tdq.common.model.avro.DeviceDetection.Builder setModel(java.lang.String value) {
      validate(fields()[2], value);
      this.model = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'model' field has been set.
      * @return True if the 'model' field has been set, false otherwise.
      */
    public boolean hasModel() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'model' field.
      * @return This builder.
      */
    public com.ebay.dap.tdq.common.model.avro.DeviceDetection.Builder clearModel() {
      model = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public DeviceDetection build() {
      try {
        DeviceDetection record = new DeviceDetection();
        record.formFactor = fieldSetFlags()[0] ? this.formFactor : (java.lang.String) defaultValue(fields()[0]);
        record.experience = fieldSetFlags()[1] ? this.experience : (java.lang.String) defaultValue(fields()[1]);
        record.model = fieldSetFlags()[2] ? this.model : (java.lang.String) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<DeviceDetection>
    WRITER$ = (org.apache.avro.io.DatumWriter<DeviceDetection>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<DeviceDetection>
    READER$ = (org.apache.avro.io.DatumReader<DeviceDetection>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.formFactor == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.formFactor);
    }

    out.writeString(this.experience);

    if (this.model == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.model);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.formFactor = null;
      } else {
        this.formFactor = in.readString();
      }

      this.experience = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.model = null;
      } else {
        this.model = in.readString();
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.formFactor = null;
          } else {
            this.formFactor = in.readString();
          }
          break;

        case 1:
          this.experience = in.readString();
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.model = null;
          } else {
            this.model = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










