flink:
  app:
    name: Flink Kafka Consumer Test
#    checkpoint:
#      data-dir: /tmp/flink/checkpoints/my-local-flink-job/
#    parallelism:
#      default: 1
#      source: 10
#    watermark:
#      max-out-of-orderness-in-min: 3
#      idle-source-timeout-in-min: 10
    source:
      kafka:
        group-id: stage-kafka-consumer-test
        env: stage
        stream: behavior.totalv2
        dc: slc
        topic:
          - behavior.totalv2.test
        from-timestamp: latest

rheos:
  client:
    auth-type: TRUST_FABRIC
#    iaf:
#      id: "urn:ebay-marketplace-consumerid:68a97ac2-013b-4915-9ed7-d6ae2ff01618"
#      secret: 6218c197-200e-49d7-b404-2a4dbf7595ef
#      env: staging
    tf:
#      app-id: yxiao6-local-flink-app
      env: stage


#kafka:
#  consumer:
#    max-poll-records: 3000
#    # 16MB, default value is 50MB
#    fetch-max-bytes: 16777216
#    # 128KB, default value is 64KB
#    receive-buffer: 131072
#    fetch-max-wait-ms: 100
#    # 4MB, default value is 1MB
#    max-partitions-fetch-bytes: 4194304
#    auto-offset-reset: latest