/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.ebay.dap.tdq.common.model.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** This category of cols are used for event correlation in stateful processor
*  It won't output in singal delta but for stateful processor internal usage */
@org.apache.avro.specific.AvroGenerated
public class CorrelationContext extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4209548916546497787L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CorrelationContext\",\"namespace\":\"com.ebay.dap.tdq.common.model.avro\",\"doc\":\"This category of cols are used for event correlation in stateful processor\\n*  It won't output in singal delta but for stateful processor internal usage\",\"fields\":[{\"name\":\"ciid\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"trackableId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"pageViewId\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null},{\"name\":\"siid\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CorrelationContext> ENCODER =
      new BinaryMessageEncoder<CorrelationContext>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CorrelationContext> DECODER =
      new BinaryMessageDecoder<CorrelationContext>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CorrelationContext> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CorrelationContext> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CorrelationContext> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<CorrelationContext>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CorrelationContext to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CorrelationContext from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CorrelationContext instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CorrelationContext fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Long ciid;
   private java.lang.String trackableId;
   private java.lang.String pageViewId;
   private java.lang.String siid;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CorrelationContext() {}

  /**
   * All-args constructor.
   * @param ciid The new value for ciid
   * @param trackableId The new value for trackableId
   * @param pageViewId The new value for pageViewId
   * @param siid The new value for siid
   */
  public CorrelationContext(java.lang.Long ciid, java.lang.String trackableId, java.lang.String pageViewId, java.lang.String siid) {
    this.ciid = ciid;
    this.trackableId = trackableId;
    this.pageViewId = pageViewId;
    this.siid = siid;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ciid;
    case 1: return trackableId;
    case 2: return pageViewId;
    case 3: return siid;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ciid = (java.lang.Long)value$; break;
    case 1: trackableId = value$ != null ? value$.toString() : null; break;
    case 2: pageViewId = value$ != null ? value$.toString() : null; break;
    case 3: siid = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'ciid' field.
   * @return The value of the 'ciid' field.
   */
  public java.lang.Long getCiid() {
    return ciid;
  }


  /**
   * Sets the value of the 'ciid' field.
   * @param value the value to set.
   */
  public void setCiid(java.lang.Long value) {
    this.ciid = value;
  }

  /**
   * Gets the value of the 'trackableId' field.
   * @return The value of the 'trackableId' field.
   */
  public java.lang.String getTrackableId() {
    return trackableId;
  }


  /**
   * Sets the value of the 'trackableId' field.
   * @param value the value to set.
   */
  public void setTrackableId(java.lang.String value) {
    this.trackableId = value;
  }

  /**
   * Gets the value of the 'pageViewId' field.
   * @return The value of the 'pageViewId' field.
   */
  public java.lang.String getPageViewId() {
    return pageViewId;
  }


  /**
   * Sets the value of the 'pageViewId' field.
   * @param value the value to set.
   */
  public void setPageViewId(java.lang.String value) {
    this.pageViewId = value;
  }

  /**
   * Gets the value of the 'siid' field.
   * @return The value of the 'siid' field.
   */
  public java.lang.String getSiid() {
    return siid;
  }


  /**
   * Sets the value of the 'siid' field.
   * @param value the value to set.
   */
  public void setSiid(java.lang.String value) {
    this.siid = value;
  }

  /**
   * Creates a new CorrelationContext RecordBuilder.
   * @return A new CorrelationContext RecordBuilder
   */
  public static com.ebay.dap.tdq.common.model.avro.CorrelationContext.Builder newBuilder() {
    return new com.ebay.dap.tdq.common.model.avro.CorrelationContext.Builder();
  }

  /**
   * Creates a new CorrelationContext RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CorrelationContext RecordBuilder
   */
  public static com.ebay.dap.tdq.common.model.avro.CorrelationContext.Builder newBuilder(com.ebay.dap.tdq.common.model.avro.CorrelationContext.Builder other) {
    if (other == null) {
      return new com.ebay.dap.tdq.common.model.avro.CorrelationContext.Builder();
    } else {
      return new com.ebay.dap.tdq.common.model.avro.CorrelationContext.Builder(other);
    }
  }

  /**
   * Creates a new CorrelationContext RecordBuilder by copying an existing CorrelationContext instance.
   * @param other The existing instance to copy.
   * @return A new CorrelationContext RecordBuilder
   */
  public static com.ebay.dap.tdq.common.model.avro.CorrelationContext.Builder newBuilder(com.ebay.dap.tdq.common.model.avro.CorrelationContext other) {
    if (other == null) {
      return new com.ebay.dap.tdq.common.model.avro.CorrelationContext.Builder();
    } else {
      return new com.ebay.dap.tdq.common.model.avro.CorrelationContext.Builder(other);
    }
  }

  /**
   * RecordBuilder for CorrelationContext instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CorrelationContext>
    implements org.apache.avro.data.RecordBuilder<CorrelationContext> {

    private java.lang.Long ciid;
    private java.lang.String trackableId;
    private java.lang.String pageViewId;
    private java.lang.String siid;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.ebay.dap.tdq.common.model.avro.CorrelationContext.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ciid)) {
        this.ciid = data().deepCopy(fields()[0].schema(), other.ciid);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.trackableId)) {
        this.trackableId = data().deepCopy(fields()[1].schema(), other.trackableId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.pageViewId)) {
        this.pageViewId = data().deepCopy(fields()[2].schema(), other.pageViewId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.siid)) {
        this.siid = data().deepCopy(fields()[3].schema(), other.siid);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing CorrelationContext instance
     * @param other The existing instance to copy.
     */
    private Builder(com.ebay.dap.tdq.common.model.avro.CorrelationContext other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.ciid)) {
        this.ciid = data().deepCopy(fields()[0].schema(), other.ciid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.trackableId)) {
        this.trackableId = data().deepCopy(fields()[1].schema(), other.trackableId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.pageViewId)) {
        this.pageViewId = data().deepCopy(fields()[2].schema(), other.pageViewId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.siid)) {
        this.siid = data().deepCopy(fields()[3].schema(), other.siid);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'ciid' field.
      * @return The value.
      */
    public java.lang.Long getCiid() {
      return ciid;
    }


    /**
      * Sets the value of the 'ciid' field.
      * @param value The value of 'ciid'.
      * @return This builder.
      */
    public com.ebay.dap.tdq.common.model.avro.CorrelationContext.Builder setCiid(java.lang.Long value) {
      validate(fields()[0], value);
      this.ciid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ciid' field has been set.
      * @return True if the 'ciid' field has been set, false otherwise.
      */
    public boolean hasCiid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ciid' field.
      * @return This builder.
      */
    public com.ebay.dap.tdq.common.model.avro.CorrelationContext.Builder clearCiid() {
      ciid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'trackableId' field.
      * @return The value.
      */
    public java.lang.String getTrackableId() {
      return trackableId;
    }


    /**
      * Sets the value of the 'trackableId' field.
      * @param value The value of 'trackableId'.
      * @return This builder.
      */
    public com.ebay.dap.tdq.common.model.avro.CorrelationContext.Builder setTrackableId(java.lang.String value) {
      validate(fields()[1], value);
      this.trackableId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'trackableId' field has been set.
      * @return True if the 'trackableId' field has been set, false otherwise.
      */
    public boolean hasTrackableId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'trackableId' field.
      * @return This builder.
      */
    public com.ebay.dap.tdq.common.model.avro.CorrelationContext.Builder clearTrackableId() {
      trackableId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'pageViewId' field.
      * @return The value.
      */
    public java.lang.String getPageViewId() {
      return pageViewId;
    }


    /**
      * Sets the value of the 'pageViewId' field.
      * @param value The value of 'pageViewId'.
      * @return This builder.
      */
    public com.ebay.dap.tdq.common.model.avro.CorrelationContext.Builder setPageViewId(java.lang.String value) {
      validate(fields()[2], value);
      this.pageViewId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'pageViewId' field has been set.
      * @return True if the 'pageViewId' field has been set, false otherwise.
      */
    public boolean hasPageViewId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'pageViewId' field.
      * @return This builder.
      */
    public com.ebay.dap.tdq.common.model.avro.CorrelationContext.Builder clearPageViewId() {
      pageViewId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'siid' field.
      * @return The value.
      */
    public java.lang.String getSiid() {
      return siid;
    }


    /**
      * Sets the value of the 'siid' field.
      * @param value The value of 'siid'.
      * @return This builder.
      */
    public com.ebay.dap.tdq.common.model.avro.CorrelationContext.Builder setSiid(java.lang.String value) {
      validate(fields()[3], value);
      this.siid = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'siid' field has been set.
      * @return True if the 'siid' field has been set, false otherwise.
      */
    public boolean hasSiid() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'siid' field.
      * @return This builder.
      */
    public com.ebay.dap.tdq.common.model.avro.CorrelationContext.Builder clearSiid() {
      siid = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CorrelationContext build() {
      try {
        CorrelationContext record = new CorrelationContext();
        record.ciid = fieldSetFlags()[0] ? this.ciid : (java.lang.Long) defaultValue(fields()[0]);
        record.trackableId = fieldSetFlags()[1] ? this.trackableId : (java.lang.String) defaultValue(fields()[1]);
        record.pageViewId = fieldSetFlags()[2] ? this.pageViewId : (java.lang.String) defaultValue(fields()[2]);
        record.siid = fieldSetFlags()[3] ? this.siid : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CorrelationContext>
    WRITER$ = (org.apache.avro.io.DatumWriter<CorrelationContext>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CorrelationContext>
    READER$ = (org.apache.avro.io.DatumReader<CorrelationContext>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    if (this.ciid == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.ciid);
    }

    if (this.trackableId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.trackableId);
    }

    if (this.pageViewId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.pageViewId);
    }

    if (this.siid == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.siid);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (in.readIndex() != 1) {
        in.readNull();
        this.ciid = null;
      } else {
        this.ciid = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.trackableId = null;
      } else {
        this.trackableId = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.pageViewId = null;
      } else {
        this.pageViewId = in.readString();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.siid = null;
      } else {
        this.siid = in.readString();
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (in.readIndex() != 1) {
            in.readNull();
            this.ciid = null;
          } else {
            this.ciid = in.readLong();
          }
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.trackableId = null;
          } else {
            this.trackableId = in.readString();
          }
          break;

        case 2:
          if (in.readIndex() != 1) {
            in.readNull();
            this.pageViewId = null;
          } else {
            this.pageViewId = in.readString();
          }
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.siid = null;
          } else {
            this.siid = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










